liblouis/liblouisutdml

liblouisutdml/logging.c
defaultLogCallback is declared in logging.c, line 63 as taking `int
level`, but then defined on line 130 as taking `logLevels level`.
The declaration (unlike) is correct, because defaultLogCallback is
assigned to variable of type `logcallback` on line 65, and `logcallback`
takes `int`, not `logLevels` (see liblouis' logging.c, line 157).
This should fix compilation errors in Travis for the LCG library -
currently it produces this error when compiling with master version of
liblouisutdml with master version of liblouis:
```
logging.c:130:1: error: conflicting types for ‘defaultLogCallback’
logging.c:63:13: note: previous declaration of ‘defaultLogCallback’ was here
logging.c:63:13: warning: ‘defaultLogCallback’ used but never defined [enabled by default]
```
You can see this error here: …
=> Fix log level type in default callback

windows/include/config.h
From MSVC 14.0 redefining snprintf to _snprintf does not work but C99 support is supported and is the preferred solution
If an ELSE can be used even better!
=> redefine snprintf no longer supported

m4/ax_jni_include_dir.m4
Starting with OS 10.8, Java header files are no longer located in or symlinked to:
```
/System/Library/Frameworks/JavaVM.framework/Headers
```
Instead, they are located within the Xcode bundle:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/*.sdk/System/Library/Frameworks/JavaVM.framework/Headers
```
For this reason, `configure` will fail to locate `jni.h` on all recent versions of OS X.
This change simply sets the search path for Java includes to `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/*.sdk/System/Library/Frameworks/JavaVM.framework/Headers` if the host system is running OS X 10.8 or later.
=> Fix for locating Java headers in OS X versions greater than 10.7.

liblouisutdml/transcribe_paragraph.c
Force Footer to have value KeepWithNext=1 so paragraphs which have keepWithNext before footer roll-over to next page.
=> Fix so footer doesn't stop KeepWithNext working

m4/ax_jni_include_dir.m4
These changes to `ax_jni_include_dir.m4` are needed in order to allow Java headers to be properly located on macOS when compiling.
Tested on OS X 10.6 through 10.11. Also tested for regressions on Ubuntu and Windows.
I am also submitting the updated `ax_jni_include_dir` to the Autoconf Archive.
If we're going to do a new release of liblouisutdml in the near-future to support Liblouis 3, it would be great to merge this first.
=> Fixes for java detection on macOS

liblouisutdml/louisutdml.h, liblouisutdml/readconfig.c
After Liblouis 3.2.0 release published, Liblouis UTDML master branch version doesn't compiled right.
This little fix solves this issue, based with Liblouis list thread suggestions.
Original Liblouis UTDML source tree when compilation happening, the compiler doesn't founding the „louis.h” header file, and some Liblouis functions names changed since Liblouis 3.2.0 release.
I used the suggested fix since more months my Ubuntu 16.04 based system, and using Liblouis 3.2.0 release.
Without this fix, Liblouis UTDML doesn't compiled my system. When I using the suggested fix, the compilation happening wonderful.
Please review this fix, and if pass this fix the reviewing, please commit this fix into Liblouis UTDML master branch.
=> Fix Liblouisutdml incompatibility with newest Liblouis 3.2.0 and future 3.3.0 release

liblouisutdml/transcriber.c
12 seems like a typo, it's a way too big number, libreoffice uses 2 for
instance.
=> hyphenation: fix MIN_NEXT_LINE to 2

lbu_files/document-content.sem, liblouisutdml/examine_document.c, liblouisutdml/louisutdml.h, liblouisutdml/makeContents.c, liblouisutdml/readconfig.c, liblouisutdml/transcriber.c
LibreOffice documents do not provide explicit page numbers, but provides
the pagebreak points, so liblouisutdml can simply count the page
numbers.
=> Support automatic page numbering

liblouisutdml/logging.c, tests/run_test.sh, tools/file2brl.c
This reduces the amount of logging output that `file2brl` generates. 
This PR replaces #52
=> Set the default log level to WARN

liblouisutdml/semantics.c
"which" should can not be equal to the number of inserts.
The issue was detected by using CFLAGS=-fsanitize=address while running
test_mathml_woluwe/test_089.test and test_mathml_woluwe/test_097.test:
```
==522849==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6070000011f0 at pc 0x7fc48ececed1 bp 0x7ffe9fc17990 sp 0x7ffe9fc17988
READ of size 4 at 0x6070000011f0 thread T0
#0 0x7fc48ececed0 in insert_code /tmp/liblouisutdml-2.8.0/liblouisutdml/semantics.c:537
#1 0x7fc48ed00f79 in transcribe_math /tmp/liblouisutdml-2.8.0/liblouisutdml/transcribe_math.c:87
#2 0x7fc48ed01046 in transcribe_math /tmp/liblouisutdml-2.8.0/liblouisutdml/transcribe_math.c:92
#3 0x7fc48ed01046 in transcribe_math /tmp/liblouisutdml-2.8.0/liblouisutdml/transcribe_math.c:92
#4 0x7fc48ecff995 in …
```
=> Fix buffer overflow

liblouisutdml/makeEndnotes.c, liblouisutdml/semantics.c
xmlGetProp (and thus get_attr_value) return a newly-allocated string. We
thus have to free it.
Fixes #77
=> Add missing xmlFree

Dockerfile.win32, Dockerfile.win64
Hi Chris or any maintainer,
Hopefully this change rans correctly with online build workflows.
If yes, please apply the Liblouisutdml master branch this simple commit, and if this is possible, generate a new stable Liblouisutdml 3.12.0 version with based Liblouis latest 3.24.0 release for 64 bit Windows operating systems and 32 bit Windows operating systems.
Linux related binary build is not a problem, because if present a new stable source code version, distro maintainers will doing Linux related packages.
My committed change not do a drastical change, only updated with DOCKERfile.win32 and DOCKERFILE.win64 the Liblouis version from 3.21.0 version to latest 3.24.0 version.
Why very need this change (only my openion)?
Since Liblouisutdml version 3.11.0 are released ( in 2022. March 0), …
=> Update Docker files to latest 3.24 Liblouis version

.github/workflows/main.yml, Dockerfile.win32, Dockerfile.win64
Hi Chris,
As it is usual, I updated the Liblouis stable version from 3.25.0 to 3.26.0 version into Dockerfile.win32, Dockerfile.win64 and .github/workflow/main.yml file.
The patch not too long, few lines only. If you have a little time, please review this patch and approve this change into the Liblouis UTDML master branch.
The Liblouis version update is need for Liblouis UTDML, because Liblouis 3.26 release contains larger improvements with Braille-tables related, for example hungarian, nemeth Braille tables.
After the update is happen, because not have other opened issues perhaps need do a new Liblouis UTDML release, because I thing Liblouis UTDML previous 2.11.0 release uses Liblouis 3.20.0 and publicated in 2022. march 8.
The make distwin command ran my machine succesfull.
congratulate …
=> Update Liblouis version with 3.26 version the important build files

.github/workflows/main.yml, .github/workflows/sanitizer.yml, Dockerfile.win32, Dockerfile.win64, lbu_files/wiskunde.ctb, tests/Makefile.am, tests/test_mathml_woluwe/liblouisutdml.ini
Hi Boys,
As it is usual, I updated after Liblouis 3.27.0 release publication the Liblouis UTDML used stable version from 3.26.0 version to 3.27.0 version.
The first commit affected  files:
* .github/workflows/main.yml,
* .github/workflows/sanitizer.yml
The second commit resolves 25 failed voluve test files failures related issue after 3.27.0 version migration, the diff output is showed @bertfrees in Liblouis issue [#1434](https://github.com/liblouis/liblouis/issues/1434).
The second commit fixes [Liblouis issue #1434](https://github.com/liblouis/liblouis/issues/1434)
My machine make distwin command ran succesfull.
Attila
=> Update Liblouis stable version from 3.26.0 to 3.27.0 version

.github/workflows/main.yml, .github/workflows/sanitizer.yml, Dockerfile.win32, Dockerfile.win64, tests/Makefile.am
Hi Boys,
As it is usual after new Liblouis stable release publication, I updated into Liblouisutdml source tree the proper files to synchronise the version number the new version (now with increasing Liblouis version number from 3.27.0 to 3.28.0 version number).
If this is possible, please approve and merget this little changes the master branch.
Affected files:
* .github/workflows/main.yml,
* .github/workflows/sanitizer.yml.
If future the community would like publicating a new Liblouisutdml release (after 2024. march or 2024. june for example), better to syncing the Liblouis version number the actual stable release.
Note: anybody not known an automatic possibility, similar with dependabot handles the required dependency versions in Liblouis to …
=> Increase Liblouis version number to 3.28.0 version

liblouisutdml/liblouisutdml.c, liblouisutdml/transcriber.c, liblouisutdml/utd2brf.c, liblouisutdml/utd2dsbible.c, liblouisutdml/utd2pef.c, liblouisutdml/utd2transinxml.c, liblouisutdml/utd2volumes.c
Fix building with latest libxml2 2.12.x and gcc 14.x `-Wimplicit-function-declaration` warning.
<details>
<summary>Without those fixes build fails with
</summary>
```console
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/liblouisutdml-2.12.0/liblouisutdml'
/bin/sh ../libtool  --tag=CC   --mode=compile /usr/bin/gcc -DHAVE_CONFIG_H -I.  -I.. -DLBU_PATH=\"/usr/share/liblouisutdml/lbu_files/\" -DLIBLOUIS_TABLES_PATH=\"/usr/share/liblouis/tables/\" -DLBULIB  -I/usr/include/liblouis -I/usr/include/libxml2 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -O2 -g -grecord-gcc-switches -pipe -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fdata-sections -ffunction-sections …
```
=> fix -Wimplicit-function-declaration warnings

.github/workflows/main.yml, .github/workflows/sanitizer.yml, Dockerfile.win32, Dockerfile.win64
Hy Boys,
As it is usual, I updated Liblouis stable version number with 3.29.0 version after @egli publicated the new great stable version. :-):-)
Following files are affected (as it is usual after new Liblouis release coming out):
* .github/workflows/main.yml,
* .github/workflows/sanitizer.yml
If all checks are passed, please merge this PR with master branch if you have a little time.
I don't no when would like publicate the community a new 2.13.0 Liblouisutdml version, so this is a safe purpose pull request to follow up stable Liblouis version number change.
Many new tables are added the Liblouis 3.29.0 release, and many tables are larger modified (for example the turkish 8 dot table, grade 1 and grade 2 tables with Oguz Ogur doed).
If now not yet …
=> Update Liblouis stable version to 3.29.0

.github/workflows/main.yml, .github/workflows/sanitizer.yml, Dockerfile.win32, Dockerfile.win64, lbu_files/wiskunde.ctb
In dutch table changed the underscore virtual dot from 4569 to 456a with Liblouis 3.30 release. Without this change follow up in Liblouisutdml, 18 voluve math tests are failing. Fixes issue #106
Thanks Bert the help! :-):-)
Attila
=> lbu_files/wiskunde.ctb: Replace dot 4569 to 456a (underscore simbol)

java/Jliblouisutdml.c
With -Wincompatible-pointer-types gcc 14 complains.
=> Fix callback type

.github/workflows/main.yml, .github/workflows/sanitizer.yml, Dockerfile.win32, Dockerfile.win64
Hi Boys,
@egli, @bertfrees, as it is usual after new Liblouis stable release publication, I updated Liblouis version number from 3.30.0 version to 3.31.0 version with following build files:
* .github/workflow/main.iml,
* .github/workflow/sanitizer.yml
My local system first upgraded Liblouis package to the new 3.31.0 stable version, and after this, before I doing build file changes, I ran a ./autogen.sh --prefix=/usr, ./configure --prefix=/usr, make, and a make check commands.
I verifyed the tests/test-suite.log, my local system I see following informations, hopefully online workflows produce similar results:
```
================================================
liblouisutdml 2.13.0: tests/test-suite.log …
```
=> Update Liblouis stable version number from 3.30.0 to 3.31.0 version with required build files

.github/workflows/main.yml, .github/workflows/sanitizer.yml, Dockerfile.win32, Dockerfile.win64
Hi Boys,
As it is usual, when a new important Liblouis stable version come out, I update Liblouis latest stable version number with affected Liblouisutdml build files the latest stable version (now from the 3.31.0 Liblouis version to the 3.32.0 version):
* .github/workflows/main.yml,
* .github/workflows/sanitizer.yml.
Me my local system after I upgrade Liblouis version to the latest stable release, Liblouisutdml compilation ran successfull (make check, tests/make check commands).
I suggests a thing if this is possible:
Because latest Liblouisutdml stable version are released in 2023. november (the 2.12.0 version), and this version are supports with Liblouis 3.27.0 version (this is importanter with in Windows systems), perhaps good to release a new …
=> Update latest Liblouis stable version number with affected build files

liblouisutdml/liblouisutdml.c, liblouisutdml/louisutdml.h
libxml before 2.14 used to define it, but it's not part of its API, so we shouldn't have been using it.
Fixes #118
=> libxml_errors: drop ATTRIBUTE_UNUSED
